### ISSUE TITLE
[Feature Request] Virtual Color Mixer

### ISSUE THREAD

**Issue by alexanderpas** [tobspr-games/shapez.io#1032]
Every building which modifies items has an virtual equivalent for use on the wires layer, except for the color mixer.

The addition of the virtual color mixer would allow for the creation of universal color mixers without contant signals, where if given all 3 if the basic paint inputs, it would be able to create any given color, no matter in which belt contains which color of paint.

**Comment by darkwater4213** [comment]
Hmm. Shouldn't be too hard to implement, I'll see if I can do that for you and open a PR. (Don't expect it to be fast though. Sorry about that.)

**Comment by Alex-x90** [comment]
Could be nice to have as a building but is already possible via logic: 
![image](https://user-images.githubusercontent.com/40383341/111386406-75255100-8669-11eb-9226-0bf038296330.png)

**Comment by darkwater4213** [comment]
You do realize that this would be a pain to construct the first time in every MAM map that you have (with plenty of room for human error) and that it takes up massive amounts of space, not to mention that it has about a half-second of ping, right? (No offense... Just pointing out that it isn't exactly a totally viable solution...)

**Comment by EmeraldBlock** [comment]
In a MAM, all you should need to do is decompose a color into its RGB components, which shouldn't be too hard (only requires that bottom left or bottom right module)

**Comment by darkwater4213** [comment]
But it's still complicated. There's an unstacker; why not a mixer (or even an un-mixer?)

**Comment by EmeraldBlock** [comment]
because the other ones are infeasible to make

**Comment by darkwater4213** [comment]
Not really. The virtual mixer would work much the same as the normal, and the un-mixer would just return two reds if it were given a red.

**Comment by EmeraldBlock** [comment]
huh? I mean that you can't make virtual stackers, unstackers, rotators, or painters without manually accounting for about every shape (due to floating layer stuff, and even ignoring that it would be much more complicated)

**Comment by Alex-x90** [comment]
While a virtual color mixer could be nice to have in niche situations, it's borderline useless. Most MAMs don't even use smart mixers, and even if you are using a smart mixer it's easily possible to do so without a virtual color mixer. What emerald block meant is that a virtual color mixer/unmixer is entirely possible only with (relatively) small logic, while all other types of operations (virtual stackers, painters, cutters, etc.) would essentially require you to make an absolutely enormous lookup table with every possible shape input, making them infeasible to do with logic.

**Comment by dengr1065** [comment]
As described above, additionally a virtual color mixer is present in Wires+.
