### ISSUE TITLE
Feature Request: Pulses and toggle switches

### ISSUE THREAD

**Issue by bckspc** [tobspr-games/shapez.io#1049]
Similar to the existing buttons but with an input to toggle the value based on wires instead of the user pressing the button. This would work with a pulse.

**Pulse:** Basically when an event happens (storage is full, item x passes through a counter, etc) a pulse of 1 would be sent via a wire.
**Toggle switch:** could be a normal button with a wire input. Whenever we receive a pulse the state would change from 1 to 0 or from 0 to 1.

This would be very usefull with variant capacity storage (see https://github.com/tobspr/shapez.io/issues/561).

**Comment by edorfaus** [comment]
What you're calling a toggle switch can already be built using the existing logic gates and/or transistors, in several ways. That kind of circuit is a fairly common building block in digital electronics, known under several names - e.g. frequency divider, flip-flop, or counter, depending on the details - and can be built much the same way in the game. I've built several variants in the game myself, including combining some of them into multi-bit counters and using them to count the shapes passing through a belt reader (via a compare block to count just that shape).

I'll admit that even my smallest variant takes rather more space than a single building would, though, so it would certainly be convenient to have it packaged up like that. (But that's true of a lot of things.)

Regarding pulses, right now most of the buildings seem to work more with levels than pulses - e.g. the storage outputs 1 as long as it is full, and the belt reader outputs 1 as long as any element is passing through, with no 0 between packed items. (That last bit is something I had to work around for my item counter, which forced me to use only half of the belts throughput.)

I think that for the storage, the current behavior makes more sense than a pulse (and a signal edge is pretty easy to turn into a short pulse anyway), but I _would_ like to see the belt reader support sending per-item pulses.

(I'd also like to have a momentary pulse button that only outputs 1 as long as it is held down (for manual triggers), to avoid needing to click twice (on then off), but I'd say that's a related-but-separate issue, and not as important.)

**Comment by bckspc** [comment]
I'll investigate the flip-flop, counters, etc.
Regarding the storage, I like and use the current behavior, my suggestion was to add another wire point with the count or another building with that feature (although I think this would be too much work). My only objective was to do something like if count > x then release (set filter to open), and do this in a small package since doing all the wire logic is very painful atm with all the possible connect points that each object has.

:D

**Comment by dengr1065** [comment]
Both are possible as a circuit in vanilla and exist as a single building in mods such as Wires+.
