### ISSUE TITLE
Feature Request: Colored lanes and Labels

### ISSUE THREAD

**Issue by bckspc** [tobspr-games/shapez.io#1050]
Hi, don't know if this was mention before. I've tried searching the issues and couldn't find it.

1. **Colored lanes:** if we could assign a specific color to a lane it would be helpful when the lane is empty to know what that lane would transport. Example: I have a factory far from the source of materials and one of the lanes is empty and I cannot immediately identify what that lane was transporting without going all the way back to the source. Also this would help as well when zooming out.
2. **Labels**: I see this as code comments, it would be helpful sometimes to label specific lanes or buttons to understand what they do. This is different from the zoom-out tags. The labels would only show when seeing the buildings. Example: button that is connected to a filter that let's item pass through or send them to the trash. Label below saying "Move to trash".

**Comment by chunkybanana** [comment]
There's the [colorcoded](https://skimnerphi.net/mods/colorcoded) and [in game notes](https://shapez.old.mod.io/in-game-notes)  mods which do the two things you ask.

**Comment by bckspc** [comment]
Nice. Thanks!
