### ISSUE TITLE
[Feature Request] Add Notes To Map

### ISSUE THREAD

**Issue by Arescet** [tobspr-games/shapez.io#1071]
Maybe this is a sign of my horrible organizing skills, but the ability to add text boxes to your map that you can write into to jot down to-do, what something does etc.

Similar to the current marker system, but without clogging up the list of spots to go to. Could be able to allow new lines and longer strings, as the text fitting into the marker list neatly wouldn't be an issue.

Could even read shape keys in the text and convert them into icons in the text box, as a sort of rich-text. This part seems more annoying to add though.

**Comment by dengr1065** [comment]
Partially implemented in a mod: <https://mod.io/g/shapez/m/in-game-notes>.
