### ISSUE TITLE
[Feature Request] add RS, D and T flipflops, and 4/8b counter and databus with its connector

### ISSUE THREAD

**Issue by primer97** [tobspr-games/shapez.io#1073]
### FLIP-FLOPS

please add These flipflop:
**RS FlipFlop**
input: R, S
output: Q
note: very usefull for memorisation

**D FlipFlop**
input: D, clock, R, S
output: Q
note: very usefull for counter, shift register

**Toggle FlipFlop***
input:T, clock
output: Q, non-Q

reference : https://en.wikipedia.org/wiki/Flip-flop_(electronics)

### BUS
Please add a 4bit and 8 bit databus with connector
**connector**
side1: bus plug
side2: 4 wire plugs
alternative: 8 wire plug

**bus**
a wire that transport 4 or 8 bits
that will be helpfull to transport many information, example a "7 segments digit" needs 7 bit

reference : https://www.pngegg.com/en/png-hoham

### COUNTER
a binary counter,
input: clock, Reset
output: 4 (or 8) wires (we can plug 2nd side of a bus connector)

**Comment by jw2476** [comment]
All of this is already possible with the logic gates available, and this is only useful for computers and would add very little to the main objective of the game

**Comment by primer97** [comment]
@jw2476 yes, I know it's possible with logic gates, but require a **lot** of space. 

And about your comment related objectives of the game, 
I'm sorry but once you build your MAM, there are no more real objectives, 
so why would you like to limit imagination ? please lets choose our next objectives.

**Comment by jw2476** [comment]
If space is the main issue then a better idea would probably be to add the ability to create a circuit/ IC from a selection of logistic components. I'm not sure how feasible this would be but it would be cool?

**Comment by Alex-x90** [comment]
This seems really pointless. You can already build all these parts (some of which are actually very small) and you have literally infinite space. No reason to implement this. If you really want this you could do it as a mod (or see if someone else has already done it), but no reason to have it in the main game.

**Comment by dengr1065** [comment]
As mentioned in https://github.com/tobspr-games/shapez.io/issues/1073#issuecomment-787439611 and https://github.com/tobspr-games/shapez.io/issues/1073#issuecomment-800648410, there is no reason for these buildings to get added to the game. Some buildings mentioned here exist in Wires+ mod.
