### ISSUE TITLE
[BUG] Pasting blueprint changes beltdirection 

### ISSUE THREAD

**Issue by wspieterse** [tobspr-games/shapez.io#1121]
![afbeelding](https://user-images.githubusercontent.com/50734579/111905301-34ec1700-8a4b-11eb-8925-5901719e05dd.png)
![afbeelding](https://user-images.githubusercontent.com/50734579/111905308-3ddce880-8a4b-11eb-82ef-684736b1beae.png)
![afbeelding](https://user-images.githubusercontent.com/50734579/111905316-4c2b0480-8a4b-11eb-9b6c-0be278a9c6d7.png)

Belt direction goes down instead to the right.

**Comment by EmeraldBlock** [comment]
Duplicate of #214, duplicate of #791, duplicate of #946
