### ISSUE TITLE
Cannot set property <x> of #<Object> which has only a getter

### ISSUE THREAD

**Issue by Bagel03** [tobspr-games/shapez.io#1356]
Right now, trying to overwrite a class or anything inside of the game using `window.shapez.x = ` fails with the above error message. This seems to be a webpack problem as it errors at:
```
Object.defineProperty(exports, member, {
    get() {
        return module[member];
    },
    set(v) {
        module[member] = v; // Here
    },
});
```
I do not have any ideas to solve this, and I know it has been brought up before, but I figured I'd submit it as a formal issue for now

**Comment by dengr1065** [comment]
ESM spec does not permit such overwriting of module members, and the current implementation is non-functional.
