### ISSUE TITLE
Black background and all builds dupe and game gets really laggy

### ISSUE THREAD

**Issue by AirplanegoBrr** [tobspr-games/shapez.io#1482]
![image](https://user-images.githubusercontent.com/71111395/193668722-257c141c-1797-4590-b29b-230c96c5d55e.png)

This happens with both mods and no mods
The issue starts after reaching level 3/4 (After the cutter level and then you need to upgrade)
The game also gets really laggy (unplayable laggy)

**Comment by AirplanegoBrr** [comment]
Also to note the ss was taken with mods however I did do a test just before posting the issue (no mods in folder + restart) and the issue still happened, also a new save game was used, still same issue

**Comment by dengr1065** [comment]
Duplicate of #892 (certified Electron moment).

**Comment by AirplanegoBrr** [comment]
Ahhh thank you!
