### ISSUE TITLE
corrupte save game

### ISSUE THREAD

**Issue by seveenee** [tobspr-games/shapez.io#1498]
![image](https://user-images.githubusercontent.com/119882534/205696189-7131a3e6-33dd-499e-af71-751a95197424.png)
  

i can not play my saved game annymore can somebody pleas help me with this because i don't know hpw to fix this.

**Comment by chunkybanana** [comment]
You closed the game while it was busy saving. Nothing can be done about this.

**Comment by EmeraldBlock** [comment]
See <https://github.com/tobspr-games/shapez.io/issues/1477#issuecomment-1251426444>.
