### ISSUE TITLE
[Feature request] enable disable wire outputs

### ISSUE THREAD

**Issue by benSlaughter** [tobspr-games/shapez.io#1506]
Hi, I've got to a point where I have a lot going on, and I like to keep things compact.
However, when i have things to close together I sometimes have multiple outputs pointing to the same block.

for example:
![Screenshot_20230117_210142](https://user-images.githubusercontent.com/2961607/213011795-ac8617df-e8c1-45bf-be26-cb7dc0beeea9.png)

I could not see a way to have the colour be wired to the comparitor, without connecting to the oppersite storage.
I thought it would be handy if i could disable/switch off the bool output so that I only connect with the colour output.

Thoughts?

**Comment by EmeraldBlock** [comment]
although such a feature may be useful, it goes against the design of shapez - buildings do not have individual "settings" (except levers and constant signals, of course)

**Comment by EmeraldBlock** [comment]
separately, for your specific example:
- you don't need to explicitly compare the signals; you can just directly input the desired color signal into the filters. The filters will only let an item pass if it matches the wire signal item.
- (do not actually do this but) you actually can extract the color signal, by using a virtual painter followed by an analyzer. In this case, it faces the wrong direction though

**Comment by benSlaughter** [comment]
> you don't need to explicitly compare the signals; you can just directly input the desired color signal into the filters

🤦 ahh that makes so much sense, I thought a filter worked on a bool input :D

**Comment by benSlaughter** [comment]
> although such a feature may be useful, it goes against the design of shapez

Closing because of this good point!
