### ISSUE TITLE
Tier 7 stacker not working properly

### ISSUE THREAD

**Issue by Smedbee** [tobspr-games/shapez.io#1513]
Hello! I've found that the stacker, when at tier 7, does not go at the speed that is said in the card. At tier 7, it says it can process 1.75 
items per second. In theory, 8 of them could then fill a tier 7 belt at full speed (14 items per second -> 8 stackers x 1.75 items/s equals 14 items/s). However, when I set this up to produce this amount, I only get 12 items per second, meaning that each stacker only makes an item every 1.5 seconds, which is not correct according to the card. I saw that the double painter had an issue similar to this a few years in the past, so I thought maybe this may be something similar.

**Comment by EmeraldBlock** [comment]
Just making sure, is your belt speed sufficient?

Double painter bug is unrelated (it's due to its double output), this is probably https://github.com/tobspr-games/shapez.io/issues/781#issuecomment-717665174

**Comment by Smedbee** [comment]
> “Just making sure, is your belt speed sufficient?”

yes, it is. They processed 14 items per second, which 8 stackers at 1.75 items per second should be able to fill, without any back ups on the line, but they don’t come close to doing so.

> “Double painter bug is unrelated (it's due to its double output), this is probably https://github.com/tobspr-games/shapez.io/issues/781#issuecomment-717665174 “

Although this is something to keep in mind, in my experience this bug is not the case for what I’m experiencing. All other machines, balancers, and buildings run as I see they should, and create what my calculations say they should be able to. The only exception for this is the stacker, which consistently produces .25 items per second less than what the building card says (I have tier 8 now, and this is persistent. Card says 2 items per second, but I measure out at 1.75 items per second).

I will be able to update this thread with a screenshot of specifically what is going on at 16:00 to 17:00 EST, along with measurements and comparisons.

**Comment by Smedbee** [comment]
I have an update upon trying to get the aforementioned issue I was having...

as you stated before, it may be the issue you had mentioned after further investigation. The only difference here is that it is consistently with the stacker for me, and I don't have any problems with any of the other machines running in line with them. Since the problem is akin to the one you linked, I am going to close this issue, but I find it very strange that I only have an issue with the stackers right now, and not everything else. I would also like to mention that in my designs, there is no segment directly related with the operation of these stackers that is longer than 3 belts without something attached. I suppose it may just be something to keep in mind, for me especially...

thank you for the help you provided! It was greatly appreciated!

**Comment by EmeraldBlock** [comment]
Alright! I'll label it as a duplicate, but if you want to revisit it, feel free to share screenshots, etc. of your setups and results
