### ISSUE TITLE
cutting bug : small parts return to normal size when isolated

### ISSUE THREAD

**Issue by MyosotisArae** [tobspr-games/shapez.io#1536]
When a small part is extracted from its container and left alone, it returns to its original size. You can see it on this image : when the quater of circle is put together with the main part again, it has the same size as the big circle.
![image](https://user-images.githubusercontent.com/10477676/232021042-6c801e2b-c007-4edc-8499-d44426326776.png)

**Comment by dengr1065** [comment]
Empty layers cannot exist, the quadrant "falls" to the first layer.
