### ISSUE TITLE
inconsistent sizes after assembly

### ISSUE THREAD

**Issue by MyosotisArae** [tobspr-games/shapez.io#1537]
On this image, the white&red part has one point and two quarters of a circle. Those three partsare the same size. I put them inside a grey&blue circle that contains a point. I thought that the white&red part would be smaller than its container, since it is put inside. but the two points are the same size in the end.
Is it the expected behaviour ?
![image](https://user-images.githubusercontent.com/10477676/232030245-c1411239-dc79-4879-b15c-4781dea52f74.png)

**Comment by MyosotisArae** [comment]
Same problem when doing that way : 
![image](https://user-images.githubusercontent.com/10477676/232035795-75681721-d5e6-4642-9cb8-af058370e79a.png)

**Comment by dengr1065** [comment]
Shapes fall down when they're stacked or cut, otherwise `--CuCuCu` stacked on top of `Cu------` would result in `Cu------:--CuCuCu`, which is incorrect.
