### ISSUE TITLE
Mobile Version?!

### ISSUE THREAD

**Issue by GunniBusch** [tobspr-games/shapez.io#1544]
Hi, I think your game is really nice. But, because it is not very power intense, it should be able to run on iOS and or android? That's what I asked myself. So I used Cordova, to build a iOS and android version. For that, I compiled the source code to the web app, made some tweaks, so that it is the full version, and in the config file enabled touch support. which worked surprisingly well on an iPad in safari. 

So I used the generated built files, for Cordova. Which it allows me to build a mobile app from a js web app. Which by the way can be done all in gitpod. But the iOS app building (not the creation of the xcodeproj) can't. But I think GitHub has some way tuo automatically build an App Store version. If not, I would offer help with publishing it to the appstores.

A demo is attached (as link), but without android because (I only have it on windows, but iOS is compiled on Mac so to save time and because next week are the final exams of Highschool in Germany I didn't add it)

[Demo](https://www.icloud.com/iclouddrive/0afJasie4hr0wbBa86eHZSVqA#shapezio)
Video:

[Video](https://user-images.githubusercontent.com/47161699/233853061-f6b4032a-7e52-4680-a4f1-a0320d70d2fe.mp4)

If you have questions let me know.

**Comment by ThatOneCatboy** [comment]
Yo looks better than i thought it would, props. Worried about how performance would get in later levels, considering it *is* basically a website lol

**Comment by GunniBusch** [comment]
The Performance is actually quite good. But the game must be updated to support more touch. Because with only a touchscreen it’s not possible to rotate. But a way of multi touch gestures or to make the infoscree. In the top left corner with buttons, would do the job. Or for example to delete, make a sperrte tool. But I think that’s not that difficult, but tedious to reverse engender how it’s implemented.

**Comment by Crafter-Y** [comment]
I would really like to see this get implemented in the game. I just bought the Puzzle DLC to play in web, but unfortunately it doesn‘t work with my iPad. Maybe a disclaimer, that is wont work on iPad when accessing it from there would be nice :/

**Comment by GunniBusch** [comment]
If some is willing to make a mod, that adds button/s to the game, that when pressed, rotate the building, like pressing r. Then I would try to make a working iOS/android prototype. That can be sideloaded or if the creator of the game is willing to collaborate, I would be willing to get it to the AppStore, and of course give the earned amount to the creator. But that would be a later thing. But first, the main problem is, that there is no way without a keyboard to rotate the buildings. So a mod is key. And I really have no clue how to develop a mod so…

**Comment by GunniBusch** [comment]
> I would really like to see this get implemented in the game. I just bought the Puzzle DLC to play in web, but unfortunately it doesn‘t work with my iPad. Maybe a disclaimer, that it wont work on iPad when accessing it from there would be nice :/

Yeah technically there is a message, but on an iPad the game don’t see it’s a mobile device unlike using a cellphone

**Comment by EpicGamer243** [comment]
Has this been improved on?

**Comment by EpicGamer243** [comment]
Mabye an .ipa
