### ISSUE TITLE
Mistaken layers after trimming

### ISSUE THREAD

**Issue by KeithBH** [tobspr-games/shapez.io#1550]
As shown in the figure below, the order of two layers on the right side were changed after being trimmed.

![image](https://user-images.githubusercontent.com/82504596/236104914-74a62ed4-55f8-4161-88de-86ed248b7ec6.png)

**Comment by EmeraldBlock** [comment]
Intended (and the reason why this shape is hard). Empty layers cannot exist and are collapsed; thus, `Sr------:--------:Cw------` becomes `Sr------:Cw------`.

**Comment by KeithBH** [comment]
> Intended (and the reason why this shape is hard). Empty layers cannot exist and are collapsed; thus, `Sr------:--------:Cw------` becomes `Sr------:Cw------`.

Thanks! It helps a lot!
