### ISSUE TITLE
Any command to build an arm version App Bundle?

### ISSUE THREAD

**Issue by Williamclouf** [tobspr-games/shapez.io#1564]
found this command  `yarn gulp standalone.standalone-steam.package.darwin64` to build a standalone App Bundle, but still x86_64, is there any command to build arm64 version for Apple Silicon mac?
[#1500 ](https://github.com/tobspr-games/shapez.io/issues/1500#issuecomment-1502914831)

**Comment by Jazzzny** [comment]
Change line 108 of gulp -> standalone.js to "         * @param {'x64'|'arm64'} arch" and line 214 to ""arm64",".
With this, an Apple silicon binary will be built:
<img width="922" alt="Screenshot 2023-11-10 at 4 10 44 PM" src="https://github.com/tobspr-games/shapez.io/assets/75343012/510d6de0-8dcf-4f4f-a11e-85d8b489bca6">
