### ISSUE TITLE
Shape lost when placing a rotator in front of a storage

### ISSUE THREAD

**Issue by Hoopou** [tobspr-games/shapez.io#1568]
When you place a rotator on the input of a storage (without a belt between the rotator and the storage) where the output priority goes to a belt and the other output goes to a trash, a significant amount of items is lost. 

The amount lost is even bigger when you place 2 rotator and 2 mergers infront of a storage. 

See the image below.

Of course, all my upgrades are at the same levels... 

2023-09-16 : using lastest version of the game

![Image](https://i.imgur.com/7LQR5td.png)

**Comment by EmeraldBlock** [comment]
While I'm not sure what's with the 3rd belt from the left, I'd guess the 4th belt is due to the balancer sometimes sending in shapes at almost the same time.

**Comment by EmeraldBlock** [comment]
@Hoopou yes, that matches with what I said - by adding a single belt, the shapes are forced to wait in line before entering the storage, but with two belts, they are able to enter simultaneously

**Comment by Hoopou** [comment]
@EmeraldBlock and what about the third belt? Whats happening there?

**Comment by Hoopou** [comment]
@EmeraldBlock I thought about your comment and I don't understand how it is possible that 2 shapes enters the storage from a single belt nomather how many splitter and rotator I put infront of it since they are all at the same speed? 
It defenetly has something to do with speed, look what I found out : 

https://github.com/tobspr-games/shapez.io/assets/23001107/5a783c5a-90b5-4491-81f8-29f57964aa27

**Comment by EmeraldBlock** [comment]
I really don't know what you're saying. But there are clearly two belts entering the top storage, coming from the balancer.

**Comment by Hoopou** [comment]
never mind, its good enough for this game
