### ISSUE TITLE
Mobile: Some machines produce wrong output

### ISSUE THREAD

**Issue by MKuckert** [tobspr-games/shapez.io#1579]
I'm observing some invalid outputs for different machines, namely the cutter and the rotator, ob the Android App.

![Screenshot_20231213-161056](https://github.com/tobspr-games/shapez.io/assets/426586/ecaa9a55-8c2e-40a5-90e4-d08c66c55681)

![Screenshot_20231213-162049](https://github.com/tobspr-games/shapez.io/assets/426586/10abb174-5097-4124-bebf-32253bb52070)

The wrong behavior vanished when reloading the save game. Both behaviors happen within the same save game, but sometimes are alternating — the initial position when loading the save seems to matter, but that's just a wild guess.

I'm using version 1.0.4 on android 14 on a Google Pixel 6a

**Comment by EmeraldBlock** [comment]
for clarification: the mobile version is a complete remake of the game in Unity by the publisher Playdigious. There's an official FAQ at <https://playdigious.helpshift.com/hc/en/18-shapez/>.
