### ISSUE TITLE
I Can't Explain This

### ISSUE THREAD

**Issue by FIR3101** [tobspr-games/shapez.io#1595]
So, I was going to get a head start and start making the shapes required for future levels. When I started making the level 21 shape, I finished making the first layer. It outputed something, but not what I wanted. To be exact, the image displays the outputs that I had been given. I know the Shapez 2 demo is out but I've been on the original mainly since I can't get the Shapez 2 demo.
![Screenshot_20240307_153717_Shapez](https://github.com/tobspr-games/shapez.io/assets/162636270/444b4c6d-b348-4304-b8a6-2f8ceb0aa0f6)

**Comment by FIR3101** [comment]
Well, I restarted the game and it fixed it. I just wanted to make sure it gets patched so I don't encounter something like this again.

**Comment by EmeraldBlock** [comment]
The mobile version is an entirely separate game (a complete rewrite in Unity) by a totally different dev team. See https://github.com/tobspr-games/shapez.io/issues/1579#issuecomment-1854990663

**Comment by EmeraldBlock** [comment]
Duplicate of #1579
