### ISSUE TITLE
Modifier keys (Ctrl, Shift) don't always work on Linux (Ubuntu)

### ISSUE THREAD

**Issue by brianpeiris** [tobspr-games/shapez.io#1598]
I'm just reporting this so that other people can find it. I'm running Ubuntu 24.04 with Shapez from Steam. I ran into a bug where the game window would lose focus on almost all clicks, which would cause the Ctrl and Shift keys to not register. You can see this in windowed mode, where the game window blurs for a brief instant whenever you click on it. Sometimes the bug would even cause other windows behind the game to appear to the front. I think I was able to work around it by running in windowed mode, and just restarting the game until it stopped doing this.

**Comment by EmeraldBlock** [comment]
does this happen with other applications using Electron?

**Comment by brianpeiris** [comment]
I don't use electron apps very often, but this is the first time I've ever seen anything like this happen with any app.

**Comment by brianpeiris** [comment]
I'm going to close this, because I'm pretty sure I just saw this happen with a completely different app, so it's probably an OS level issue.
