### ISSUE TITLE
Links to Steam from the the website are broken

### ISSUE THREAD

**Issue by balexandre** [tobspr-games/shapez.io#1599]
this is true for both links:

from the website https://shapez.io/ 
both the **Play on Steam**

![Screenshot 2024-07-01 at 14 35 55](https://github.com/tobspr-games/shapez.io/assets/45473/715ebbd6-5d2a-42d8-9e02-160371457780)

as well the after we login with Steam

https://github.com/tobspr-games/shapez.io/assets/45473/29814f4c-2239-4816-802f-e43fb070b27b

**Comment by EmeraldBlock** [comment]
contacted tobspr; seems to be fixed now!
