### ISSUE TITLE
invisible hub , belts and machines 

### ISSUE THREAD

**Issue by GdGuy1** [tobspr-games/shapez.io#1601]
everything on my device is invisible except shape ores and color ores and some UI stuff 

i tried using static belts but it doesnt fix anything and im playing on mobile app
![Screenshot_20240724-195131](https://github.com/user-attachments/assets/b9033368-4307-4a4b-a40c-f160527005d2)
![Screenshot_20240724-192627](https://github.com/user-attachments/assets/b07cf306-a0c0-437c-a960-22bb3ed8bc62)

adding a screenshot of problem and screenshot of my most recent android update for my device

**Comment by EmeraldBlock** [comment]
See https://github.com/tobspr-games/shapez.io/issues/1579#issuecomment-1854990663
