### ISSUE TITLE
bad background screen updating

### ISSUE THREAD

**Issue by PulsarST** [tobspr-games/shapez.io#1609]
Than you turn off fullscreen mode and go through tutorial the background stops updating
![image](https://github.com/user-attachments/assets/2b8bd4c0-15a3-4c16-b2f6-7391a43c1fd6)

dunno why it's happened

**Comment by PulsarST** [comment]
It's steam version !

**Comment by EmeraldBlock** [comment]
See #1482, #1011, #892. Thanks for specifying steps for reproduction, but given that the cause seems to be running out of VRAM, does this consistently happen when you do that?
