### ISSUE TITLE
8 Well detailed suggestions for the wires update.

### ISSUE THREAD

**Issue by pampogokiraly** [tobspr-games/shapez.io#469]
**Hello!** (sorry for my english... i might made some mistakes :P )
I've been working on these ideas with my brother for about two weeks, and i finally finished them.
So i want to present you with a pdf file filled in with 8 well balanced (at least i think lol), well detailed (with some images too), and fun ideas :D
I really hope they help you making your game better!
(5 building, 1 setting, 2 game feature)
[Shapez.io_ideas.pdf](https://github.com/tobspr/shapez.io/files/4943574/Shapez.io_ideas.pdf)
(let me know if the link or whatever is not working... this is the first time i upload a pdf file)

Edit: Yes, i went trough all the steps and none of them has been suggested by someone else.

**Comment by PixelRifts** [comment]
Bump! This is amazing! Would like to see a few of these implemented.

**Comment by pampogokiraly** [comment]
Thank you very much PixelRifts!

**Comment by Arescet** [comment]
As for arrow keys to control, you can actually do that already in the keybind settings menu

![image](https://user-images.githubusercontent.com/24558724/88005504-89fc1580-cad7-11ea-962a-53b3752956a2.png)

**Comment by pampogokiraly** [comment]
> 
> 
> As for arrow keys to control, you can actually do that already in the keybind settings menu
I'm not talking about the movement controls... im talking about replacing the mouse with the arrow keys (so you can place down buildings without your mouse).

**Comment by tobspr** [comment]
I'll have a look!

**Comment by dengr1065** [comment]
Ended up being done in a different way. Some of these ideas can now be found in mods.
