### ISSUE TITLE
Assigning credit to upgrades and level goals

### ISSUE THREAD

**Issue by eschkufz** [tobspr-games/shapez.io#477]
Hey Developers ---

Ordinarily, sending a shape to the hub which is a prerequisite for both a level goal and an upgrade will award you credit for both. For example, sending one circle into the hub at the beginning of the game awards you credit towards *both* level 2 *and* the belts, distributor upgrade.

It's also the case that sending shapes into the hub which are prerequisites for level M when you are working towards level N (N < M) will silently accumulate credit towards level M. You can see examples of this in speedrunning where players will set up lines for level 11 and level 12 at the same time so that the targets for level 11 and level 12 are achieved at as close to the same time as possible.

Something unexpected happens if you set up a line for blue rectangles (the target shape for level 8 and the mixing painting upgrade) while you are on level 7 (this is the minimum level at which this is observable as completing level 6 unlocks painting). Rather than accumulating credit towards both the upgrade and level 8, shapes seem to only go towards the upgrade. It's only after the upgrade has been completed, that credit as awarded to the level 8 goal.

Minimal Example:

1. Be on level 7 (you've just unlocked painting and the target shape is red circle).
2. Send 1501 blue rectangles to the hub.
3. Complete level 7.

You will now be on level 8 with tier 2 mixing with only blue rectangle recorded towards the level goal. Expected behavior (as I understand it) would be 1501 rectangles recorded towards the level goal.

**Comment by immibis** [comment]
It's not actually credit. Rather, the hub actually stores the shapes and you can pay for upgrades with the shapes in the hub, and the hub needs a certain number of a certain shape to reach the next level, but you don't pay them.
