### ISSUE TITLE
Freeplay: preview next level's shape when current level's shape starts feeding

### ISSUE THREAD

**Issue by ekevoo** [tobspr-games/shapez.io#557]
At freeplay, when I finish up the production line, there's not much to do but wait.

If I try to double the production or something, by the time I'm done it'll be 80% done anyway, and much of that work is going to be wasted.

It would be helpful to know what's going to be up next as soon as the hub starts receiving my production for the current level.

**Comment by anno9474** [comment]
I would like that 👍 
would be a huge profit for the gameplay I guess

**Comment by tobspr** [comment]
Ah, well it only makes sense for freeplay since before most time you need a new building to be unlocked in order to complete the level.

**Comment by Belmakar** [comment]
Would it make sense to just have the hub output the next shape on the wires layer via an additional outlet? That way the current shape would still be front and center, while allowing advanced players to start reconfiguring their assembly line if they so desire.

You could also require unlocking free play before making it available.

**Comment by dengr1065** [comment]
[Zeitgeist](https://skimnerphi.net/mods/zeitgeist) mod partially implements this suggestion.
