### ISSUE TITLE
Windows: Alt+F4 should quit the game

### ISSUE THREAD

**Issue by ekevoo** [tobspr-games/shapez.io#577]
The vast majority of Windows games go poof within one second when I type Alt+F4. I really like this. The exceptions like to ask for a silly "are you sure" as if it was a key combination that could ever be pressed accidentally.

In Shapez.io, at least the Steam version, nothing happens when I press Alt+F4. The game doesn't react at all. Why?

**Comment by dengr1065** [comment]
Duplicate of #528
