### ISSUE TITLE
FEATURE REQUEST: Mirror Mode for Splitters, Combiners, and Mixers

### ISSUE THREAD

**Issue by iansebryk** [tobspr-games/shapez.io#586]
if it's possible and part of the game model, can you provide mirrors of the mentioned tools?  thanks.

you're probably wishing i'd never bought your game now, eh?  :D

**Comment by asdkant** [comment]
@iansebryk there's an entry on the trello for this, so it'll probably be implemented at some point: https://trello.com/c/QlYfbg9c

**Comment by Sandwichs-del** [comment]
@asdkant but title is "Allow mirroring blueprints / all buildings (spoiler: won't happen)"

**Comment by dengr1065** [comment]
Closing as duplicate of #284, not planned for the base game and has been implemented in various mods since then.
