### ISSUE TITLE
[Bug] Shape production not being added/calculated correctly in hub

### ISSUE THREAD

**Issue by Vaais** [tobspr-games/shapez.io#588]
Hi

My game only adds around 2/3 of the production to the hub. The rest vanishes in thin air.
E.g. say the info tab says 1.8k/m is being added to the hub. When I actually look at it, the number only goes up by 1.2k/m.

This has nothing to do with the (known) efficiency loss by upgrades. Because even then, these numers should be the same since neither are theoretical values, but real-time measurements. My game says 1.8 is being delivered, but it's actually 1.2 so I'm curious where the 1.8 comes from and in what void of the code the other 0.6 k/m is disappearing :P

Kind regards

**Comment by bcmpinc** [comment]
This might be due to your game being unable to keep up. I.e. it is running at 2/3 of the speed it's supposed to run at.

**Comment by Vaais** [comment]
Yes, I've noticed my game not running at the speed it should be. But even for players with performance issues, I think the number should reflect the real input of shapes to the hub. A 'real time measurement' should reflect te actual real value? Not what it could deliver when run on a better pc. That's why it's a bug.
It shouldn't change that many lines of code to correct the way the game calculates the value, i hope?

**Comment by bcmpinc** [comment]
No, all games do it like this, including Factorio which this game is based upon.

**Comment by EmeraldBlock** [comment]
See above. If the game can't run at full speed, it doesn't make sense to pretend it is.
