### ISSUE TITLE
[Feature Request] Belt intersections as a variant of tunnels

### ISSUE THREAD

**Issue by Hyperion-21** [tobspr-games/shapez.io#591]
Wire intersections but with belts instead. They would make more complex contraptions with wires easier and less jank.

**Comment by schaetzc** [comment]
Sounds good. If this was added, the next step would be two non-intersecting curves on one tile. As a single belt is already as big as a grid cell, I think both (the intersection and the non-intersection curve pair) should be buildings with in and outputs.

![curve](https://user-images.githubusercontent.com/14296809/91509425-7adc6480-e8da-11ea-852f-dd1c1e38e9e3.png)

**Comment by schaetzc** [comment]
Thinking about it, the intersection seems a bit overpowered. It should definitively be locked until the player reaches a high level. If testing shows that it makes the game too easy the building could be altered to have the following form:

![inters2](https://user-images.githubusercontent.com/14296809/91510483-7cf3f280-e8dd-11ea-8168-4276ea0c1de2.png)

This is not as wide as [tunnel entry][belt][tunnel exit] but one tile higher. The height balances things out but still allows new factory designs.

**Comment by EmeraldBlock** [comment]
Available in shapez industries; not gonna be added to vanilla though
