### ISSUE TITLE
[Feature Request] - Better Markers

### ISSUE THREAD

**Issue by AEAEAEAE4343** [tobspr-games/shapez.io#596]
Markers currently support a shape icon or a text label. I think there should be an option to have both. e.g:
![shapez marker icon](https://user-images.githubusercontent.com/34800109/91359025-18109d80-e7f4-11ea-811f-4a44e6d4b828.png)

**Comment by PyMaster22** [comment]
Good idea.

**Comment by EmeraldBlock** [comment]
Duplicate of #559
