### ISSUE TITLE
[FeatureRequest] Enhance visuals for storage building (and others)

### ISSUE THREAD

**Issue by schaetzc** [tobspr-games/shapez.io#599]
I really like the simplistic graphics of shapez.io. However, there is always room for improvement.
Especially for the storage building, as beginners (including me) seem to struggle with the overflow mechanic or don't notice it at all. If the storage building's preferred output had a slightly different design, then they might notice and understand its mechanic.  
<sub>Also, if there was a mirrored version of the storage building (at some point in the future), then the indication of the preferred output would be an absolute necessity.</sub>

Here's a proposal sketch of the storage building (in-game version on the left, non-existent mirrored version on the right);

![storage](https://user-images.githubusercontent.com/14296809/91506593-c68b1000-e8d2-11ea-96e6-f19de6a0db38.png)

**Comment by schaetzc** [comment]
Further ideas for improvements:
- The outputs on all cutting buildings (size 1x2 and 1x4) should be labeled so that the user sees which output returns which part (left/right, or up/down×left/right). I could imagine symbols like ◖/◗ and  ◴/◵/◶/◷. The symbols should not rotate with the building so that they always show the correct half/quadrant.
- The arrow direction on the rotators is hard to see when placing the building since the mouse cursor occludes most of it. Maybe the arrow head can be made thicker or the tail can be faded out / dashed. Alternatively, the mouse cursor could be hidden when placing buildings, or the building could stick to a side of the cursor instead to its center.

**Comment by PyMaster22** [comment]
![https://discord.com/assets/08c0a077780263f3df97613e58e71744.svg]

**Comment by PyMaster22** [comment]
!(thumbs up)[http://icons.iconarchive.com/icons/google/noto-emoji-people-bodyparts/1024/12008-thumbs-up-icon.png]

**Comment by dengr1065** [comment]
The artwork has been replaced in Wires update.
