### ISSUE TITLE
No-GUI mode doesn't work properly in wire layer

### ISSUE THREAD

**Issue by Hyperion-21** [tobspr-games/shapez.io#608]
![shapez_f2](https://user-images.githubusercontent.com/69665635/91626387-87f16600-e963-11ea-8090-5c7d41b5b721.png)
![shapez_f3](https://user-images.githubusercontent.com/69665635/91626388-8889fc80-e963-11ea-9a91-34cfc14b2ac4.png)
The toolbar shows when viewing the wire layer but not when viewing the main layer.

**Comment by dengr1065** [comment]
I think this is fixed now.
