### ISSUE TITLE
The filter should not be blocked when the current output lane is free

### ISSUE THREAD

**Issue by detzt** [tobspr-games/shapez.io#628]
Situation:
The input item and the logic shape of the filter differ, so the items are sent to the false-lane, which gets completely filled up.
Now the logic network changes to match the input items, so that the items should be sent to the true-lane.
However, the filter blocks and only outputs items after clearing the false-lane.

Reasoning:
For the cutter, it makes sense that all output lanes need to be free because the items have to be placed there.
But when the filter state changes, it does not matter that the unused output lane is not empty because no items are placed there.

Problems:
It is currently impossible to control a belt with the logic network, i.e. switch between enabled and disabled transportation of items.
You could place a trash at the false-lane output of the filter, but this is IMHO not a solution as that would drain the input instead of only stopping its flow.

Context:
I just finished a large factory that automatically produces the shape of the current level.
I used the filters to select which color is forwarded to the painter.

**Comment by EmeraldBlock** [comment]
tobspr stated on the shapez.io discord that he will fix this, it is indeed a strange mechanic that doesn't fit the context well

**Comment by detzt** [comment]
Okay cool, good that this is already known and discussed

**Comment by pepkin88** [comment]
You could make a loop, like this:
![image](https://user-images.githubusercontent.com/1028647/96305504-447bb580-0ffe-11eb-85f9-32fd87c07ebb.png)

It unclogs itself when switching it back.

**Comment by dengr1065** [comment]
Not sure what is the current behavior, but there won't be any further changes at this point.

**Comment by EmeraldBlock** [comment]
It appears to have been changed to match the request.
<details><summary>tested using this setup</summary>

![image](https://user-images.githubusercontent.com/69981203/201506247-edd9b82a-4cc8-4b32-905a-abcec0d4e0d2.png)
</details>
