### ISSUE TITLE
Conflict-free merging resets the size of the corners, even if they are merged with a larger side

### ISSUE THREAD

**Issue by AnthonyBATTISTINI** [tobspr-games/shapez.io#632]
merging down with middle and not get good element on top
![error shapezio](https://user-images.githubusercontent.com/50022655/92279230-2303b600-eef7-11ea-8197-675153d3b7e7.PNG)

**Comment by EmeraldBlock** [comment]
This has been "fixed" already. It's a consequence of the strange way the stacker stacks.

**Comment by MaudDibb** [comment]
then i wonder how do we solve this?

![oops](https://user-images.githubusercontent.com/7418069/95139221-9d5f6a00-0731-11eb-9cdf-73f739591784.png)

clearly this *is* an issue because how else are we supposed to get that shape to work?

**Comment by EmeraldBlock** [comment]
Swap the inputs. (I should have clarified, this has been fixed in the wires update alpha/beta version.)

**Comment by MaudDibb** [comment]
seriously? hah. ok ;)
worth giving the beta a spin? I used to do a lot of redstone work with
minecraft. wouldnt mind building a proper cpu in shapez ;)

**Comment by EmeraldBlock** [comment]
Definitely. The wires update features are pretty neat, everything has its own quirks and everything

**Comment by swear01** [comment]
I encounter a bug like this condition.
This seen to be a feature after this bug fix.
What I want to create is the lv. 18 shape.
it have no conflict, but still place one on the other one.
version: latest stable on steam

![image](https://user-images.githubusercontent.com/49574926/118390522-1fb5f200-b662-11eb-817a-9ca9dec9b5fe.png)
![image](https://user-images.githubusercontent.com/49574926/118390581-6f94b900-b662-11eb-8c36-fc1953f8ae34.png)
