### ISSUE TITLE
[Feature Request] Allow mirroring of any machine

### ISSUE THREAD

**Issue by alexisshaw** [tobspr-games/shapez.io#643]
It would be nice to be able to mirror any machine, so that for example stacking under vs over, or having the color input on the opposite side etc. This would make more compact designs without affecting the puzzles much I think.

**Comment by EmeraldBlock** [comment]
This has already been added to the Trello board (at https://trello.com/c/QlYfbg9c/270-allow-mirroring-blueprints-all-buildings)

**Comment by darkwater4213** [comment]
Huh. This would be helpful, certainly, but would take away a bit of the problem-solving involved. Maybe unlock them at a later point in the game?

**Comment by LeigerGaming** [comment]
Agreed with @darkwater4213. While I've struggled a few times to create a nice space-efficient design due to the order of inputs, I actually view this as part of the fun and challenge.

**Comment by dengr1065** [comment]
According to the [Trello card](https://trello.com/c/QlYfbg9c/270-allow-mirroring-blueprints-all-buildings), not planned for the base game. Some mods add mirrored buildings, though.
