### ISSUE TITLE
Overlapping tunnels of the same type merge together

### ISSUE THREAD

**Issue by ieee802dot11ac** [tobspr-games/shapez.io#644]
![image](https://user-images.githubusercontent.com/69217234/92536375-5cd20680-f1ee-11ea-8d48-5f8de07979f6.png)

**Comment by EmeraldBlock** [comment]
This is well-known and already fixed. Too bad, it has some neat implications.

**Comment by darkwater4213** [comment]
This is humongously helpful in some applications... Use it! Come level 14-ish, You will unlock Tunnel II, which has a longer range (8 blocks), and "ignores" the darker, shorter ones.
