### ISSUE TITLE
[Feature Request]: Sandbox Mode

### ISSUE THREAD

**Issue by kaustubhcs** [tobspr-games/shapez.io#646]
A sandbox mode where you get a completely blank map and you are able to place shape as well as color generators.

Also you are able to control speed of conveyors belts and all other components as to how many items are being processed every second.

**_Reason_**: This is a very good tool to **VISUALIZE** complex supply chain pipelines. It may actually be used for more than a game.
Can be used to create animations and visualizations of complex software programs.
_Can be used to demonstrate dataflow in complicated algorithms in computer science._

I would have done it myself, but I am not a Java script guy :)

**Comment by CodeArc13** [comment]
I would really like a sandbox mode in the steam version also, so I can mess around with the wire logic at will.

**Comment by ErneeGaming** [comment]
Same here

**Comment by ohmyshapez** [comment]
hey guys today im gonna be showing you being dumb..




























https://beta.shapez.io/v/366a2a9/?fullVersion=1&sandboxMode=1

**Comment by ohmyshapez** [comment]
THERE IS ALREADY SANDBOX MODE

**Comment by EmeraldBlock** [comment]
@ohmyshapez I believe they are referring to an even-more-customizable mode in the official release

**Comment by rylid-umil** [comment]
im gonna show you being dumb @ohmyshapez 
### **Not Found**

The requested URL was not found on this server.
_Apache Server at beta.shapez.io Port 80_

**Comment by EmeraldBlock** [comment]
the link used to work back then, but still irrelevant

**Comment by dengr1065** [comment]
Has been done in a few mods already, unlikely to happen in vanilla.
