### ISSUE TITLE
I got lost

### ISSUE THREAD

**Issue by Chivalry0** [tobspr-games/shapez.io#651]
So basically I was looking around the map for resources when I got lost and couldn't find my factory. I would like there to be an option to teleport back to the main base where you connect all of your conveyers to.

**Comment by EmeraldBlock** [comment]
Press `space`.

**Comment by ExE-Boss** [comment]
There’s also a compass arrow in the top‑right corner of the screen that points toward the **HUB**, and clicking on it will re‑center the camera on the **HUB**.
