### ISSUE TITLE
[Feature Request] Radio Control - Transmitters and Receivers

### ISSUE THREAD

**Issue by EmileAvatar** [tobspr-games/shapez.io#859]
Have 3 extra buildings.
Building: Radio Transmitter [beam]- That transmit a signal on a given frequency on a straight line (3 wide over a 50-2000 distance. 

Building: Radio Transmitter [Omnidirectional]- That transmit a signal on a given frequency on a huge eg 1000 but not as far as beam.

Building: Radio Receiver - That receives a signal on a given frequency (from beam or Omnidirectional)

The Radio frequency - Generates a frequency that a Transmitter and Receiver use. 

Inputs / Out Puts
Transmitter will have two inputs each - 1 for Frequency and 1 for Signal
Receiver with have 1 input for Frequency that it will receive from. Then output the signal from that frequency.

Reason
To allow more complex controls where wire inputs might not be possible.
Allows you to control the factory over a large distance 
The Radio will go not interfere with the wires.
However having many Radio Transmitters might interfere with one another when in close proximity.
The Radio can also go over obstacles where wires cannot go

**Comment by dengr1065** [comment]
A mod called Wires- can provide similar functionality.
